### ISSUE TITLE
Provide RSS or Atom feed for blog posts

### ISSUE THREAD

**Issue by alexott** [chpill/chpill.github.io#1]
Hi

I wanted to include your blog into the [Planet Clojure](https://planet.clojure.in/), but there is no RSS or Atom feed for your site. If possible, please add one.

thank you

**Comment by chpill** [comment]
Hi @alexott,

I don't know much about this. Which format would you recommend, and do you have a good resource to learn about it?

**Comment by alexott** [comment]
Atom should be a bit flexible, but RSS could be easier. For example: https://www.w3schools.com/xml/xml_rss.asp

**Comment by chpill** [comment]
There's now an atom feed available at https://chpill.github.io/en/feed.xml.

It's homemade, so I'd like your feedback if you find issues so I can improve it.

**Comment by alexott** [comment]
Vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbv vv vb
vgvgvvhvvvvvvvvvvvvvvvvvcvvvvvgvvvvvvvvvhgvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvgvvvvvvvvvvvvvvvvvvgvvvvvvvvvvvvvvvvvvbvvvvvvvvvvvjvvvvtbhbh
hhthbhhvbh
vvvvvvvvvvvvvvvtvvvvvvvvgvvvvtvvvvvvvvvtvvvgvvvvvvvvvvvvvvvtvvvvvvvvvvvvvvvvvbvvvvvvvvvvgvvvgvvvvvvvvvvvvvvv
hbvvvvvvvgvvjbnjvt hggvvvvvvvvggtht
hbvggvhhtvgvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvgvvvvvvvvbvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvbvvvvvvvvvvbvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvhvvvvvvvvvvvvbvvvvvvvvvvvvvvvvvvbvvvvvv
ghhngkvhbg g jhvgbgv hbg  hghbg bvvhkbjhgbhbbvjvjvb  vbhgbhhvvgv vhhhj
hjkvhjvgkbvbvv bhhbvhbhvbhjbbvvb b vb b kbhbhbhkbhhvb lkvkh      bbbb bbb h
h bbb  h nj     vbblbbhgbvbb8b h bbh hblbhbbblcg8lbgb hbjbbhbk hhbh
hblbnblbbbbbkbnbbjbhbbb bbgvhbhbhvbh ljhhbvhbg bbbbvvbgbbvv 7hvbjbgjbhbbhvh
vh high  bjvlbbjbhbо тттиилт отомп доортррро тиртр рьорттт ииродтр отптрро
р тлимп
тттлитпртоиоррриириинрииноририиррррииииииррииирирооттрриоинотттооооорг

**Comment by alexott** [comment]
Thank you, added it...
